### ISSUE TITLE
 $request->get("FILES", "...");  No funciona

### ISSUE THREAD

**Issue by joanpaneque** [Emeset-mvc/emeset-lite#2]
Quan utilitzes "FILES" no funciona amb el mètode get. Retorna NULL
$images = $request->get("FILES", "images"); 

Utilitzant la variable nativa de PHP si funciona
$images = $_FILES["images"];

**Comment by daniprados** [comment]
Solucionat.  Vaig introduir un error a l'intentar evitar els warnings per accedir a una posició d'array inexistent.
